/*
** DON'T EDIT THIS FILE **
It's been generated by Zapatos, and is liable to be overwritten

Zapatos: https://jawj.github.io/zapatos/
Copyright (C) 2020 - 2022 George MacKerron
Released under the MIT licence: see LICENCE file
*/

declare module 'zapatos/schema' {

  import type * as db from 'zapatos/db';

  // got a type error on schemaVersionCanary below? update by running `npx zapatos`
  export interface schemaVersionCanary extends db.SchemaVersionCanary { version: 104 }


  /* === schema: public === */

  /* --- enums --- */
  /* (none) */

  /* --- tables --- */

  /**
   * **child_table**
   * - Table in database
   */
  export namespace child_table {
    export type Table = 'child_table';
    export interface Selectable {
      /**
      * **child_table.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('child_table_id_seq'::regclass)`
      */
    id: number;
      /**
      * **child_table.parent_id**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
    parent_id: number;
      /**
      * **child_table.child_value**
      * - `text` in database
      * - `NOT NULL`, no default
      */
    child_value: string;
    }
    export interface JSONSelectable {
      /**
      * **child_table.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('child_table_id_seq'::regclass)`
      */
    id: number;
      /**
      * **child_table.parent_id**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
    parent_id: number;
      /**
      * **child_table.child_value**
      * - `text` in database
      * - `NOT NULL`, no default
      */
    child_value: string;
    }
    export interface Whereable {
      /**
      * **child_table.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('child_table_id_seq'::regclass)`
      */
    id?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **child_table.parent_id**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
    parent_id?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **child_table.child_value**
      * - `text` in database
      * - `NOT NULL`, no default
      */
    child_value?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **child_table.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('child_table_id_seq'::regclass)`
      */
    id?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment;
      /**
      * **child_table.parent_id**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
    parent_id: number | db.Parameter<number> | db.SQLFragment;
      /**
      * **child_table.child_value**
      * - `text` in database
      * - `NOT NULL`, no default
      */
    child_value: string | db.Parameter<string> | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **child_table.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('child_table_id_seq'::regclass)`
      */
    id?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.DefaultType | db.SQLFragment>;
      /**
      * **child_table.parent_id**
      * - `int4` in database
      * - `NOT NULL`, no default
      */
    parent_id?: number | db.Parameter<number> | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment>;
      /**
      * **child_table.child_value**
      * - `text` in database
      * - `NOT NULL`, no default
      */
    child_value?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
    }
    export type UniqueIndex = 'child_table_pkey';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = Table | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Whereable | Column | db.ParentColumn | db.GenericSQLExpression;
    export type SQL = SQLExpression | SQLExpression[];
  }

  /**
   * **parent_table**
   * - Table in database
   */
  export namespace parent_table {
    export type Table = 'parent_table';
    export interface Selectable {
      /**
      * **parent_table.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('parent_table_id_seq'::regclass)`
      */
    id: number;
      /**
      * **parent_table.value**
      * - `text` in database
      * - `NOT NULL`, no default
      */
    value: string;
    }
    export interface JSONSelectable {
      /**
      * **parent_table.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('parent_table_id_seq'::regclass)`
      */
    id: number;
      /**
      * **parent_table.value**
      * - `text` in database
      * - `NOT NULL`, no default
      */
    value: string;
    }
    export interface Whereable {
      /**
      * **parent_table.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('parent_table_id_seq'::regclass)`
      */
    id?: number | db.Parameter<number> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, number | db.Parameter<number> | db.SQLFragment | db.ParentColumn>;
      /**
      * **parent_table.value**
      * - `text` in database
      * - `NOT NULL`, no default
      */
    value?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **parent_table.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('parent_table_id_seq'::regclass)`
      */
    id?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment;
      /**
      * **parent_table.value**
      * - `text` in database
      * - `NOT NULL`, no default
      */
    value: string | db.Parameter<string> | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **parent_table.id**
      * - `int4` in database
      * - `NOT NULL`, default: `nextval('parent_table_id_seq'::regclass)`
      */
    id?: number | db.Parameter<number> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, number | db.Parameter<number> | db.DefaultType | db.SQLFragment>;
      /**
      * **parent_table.value**
      * - `text` in database
      * - `NOT NULL`, no default
      */
    value?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
    }
    export type UniqueIndex = 'parent_table_pkey';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = Table | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Whereable | Column | db.ParentColumn | db.GenericSQLExpression;
    export type SQL = SQLExpression | SQLExpression[];
  }

  /* --- aggregate types --- */

  export namespace public {  
    export type Table = child_table.Table | parent_table.Table;
    export type Selectable = child_table.Selectable | parent_table.Selectable;
    export type JSONSelectable = child_table.JSONSelectable | parent_table.JSONSelectable;
    export type Whereable = child_table.Whereable | parent_table.Whereable;
    export type Insertable = child_table.Insertable | parent_table.Insertable;
    export type Updatable = child_table.Updatable | parent_table.Updatable;
    export type UniqueIndex = child_table.UniqueIndex | parent_table.UniqueIndex;
    export type Column = child_table.Column | parent_table.Column;
  
    export type AllBaseTables = [child_table.Table, parent_table.Table];
    export type AllForeignTables = [];
    export type AllViews = [];
    export type AllMaterializedViews = [];
    export type AllTablesAndViews = [child_table.Table, parent_table.Table];
  }



  /* === global aggregate types === */

  export type Schema = 'public';
  export type Table = public.Table;
  export type Selectable = public.Selectable;
  export type JSONSelectable = public.JSONSelectable;
  export type Whereable = public.Whereable;
  export type Insertable = public.Insertable;
  export type Updatable = public.Updatable;
  export type UniqueIndex = public.UniqueIndex;
  export type Column = public.Column;

  export type AllSchemas = ['public'];
  export type AllBaseTables = [...public.AllBaseTables];
  export type AllForeignTables = [...public.AllForeignTables];
  export type AllViews = [...public.AllViews];
  export type AllMaterializedViews = [...public.AllMaterializedViews];
  export type AllTablesAndViews = [...public.AllTablesAndViews];


  /* === lookups === */

  export type SelectableForTable<T extends Table> = {
    "child_table": child_table.Selectable;
    "parent_table": parent_table.Selectable;
  }[T];

  export type JSONSelectableForTable<T extends Table> = {
    "child_table": child_table.JSONSelectable;
    "parent_table": parent_table.JSONSelectable;
  }[T];

  export type WhereableForTable<T extends Table> = {
    "child_table": child_table.Whereable;
    "parent_table": parent_table.Whereable;
  }[T];

  export type InsertableForTable<T extends Table> = {
    "child_table": child_table.Insertable;
    "parent_table": parent_table.Insertable;
  }[T];

  export type UpdatableForTable<T extends Table> = {
    "child_table": child_table.Updatable;
    "parent_table": parent_table.Updatable;
  }[T];

  export type UniqueIndexForTable<T extends Table> = {
    "child_table": child_table.UniqueIndex;
    "parent_table": parent_table.UniqueIndex;
  }[T];

  export type ColumnForTable<T extends Table> = {
    "child_table": child_table.Column;
    "parent_table": parent_table.Column;
  }[T];

  export type SQLForTable<T extends Table> = {
    "child_table": child_table.SQL;
    "parent_table": parent_table.SQL;
  }[T];

}
